//! Labels as rows: a name and a description in `labels`, and the labels an item was given in
//! `item_labels`. The move onto the core plans each project (`docket_core::migrate::plan`): an item's
//! tags and group become labels, and each central idea becomes a goal label carrying its body and is
//! dropped. A label for an area theme is left to the areas, and an item that carries a label keeps it.

use std::collections::BTreeMap;

use sea_orm::ConnectionTrait;
use sea_orm_migration::prelude::*;

use docket_core::dump::ProjectDump;
use docket_core::migrate::{Change, Rows, Rules, plan};

use crate::m20261006_000011_area_places::{drop_concept, pending, project_rows};
use crate::statement;

const UP: &str = r#"
CREATE TABLE labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  name TEXT COLLATE "C" NOT NULL CHECK (btrim(name) <> ''),
  description TEXT COLLATE "C"
);
CREATE UNIQUE INDEX labels_name ON labels(project, lower(name));

CREATE TABLE item_labels (
  rid BIGINT NOT NULL REFERENCES items(rid) ON DELETE CASCADE,
  label_id BIGINT NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
  PRIMARY KEY (rid, label_id)
);
CREATE INDEX item_labels_label ON item_labels(label_id);
"#;

const DOWN: &str = "DROP TABLE IF EXISTS item_labels; DROP TABLE IF EXISTS labels;";

const PROJECTS: &str = "SELECT slug, keys, themes, skills FROM projects ORDER BY slug";

/// A label an area theme gave, which the areas take instead.
fn is_area_theme(label: &str) -> bool {
    label.starts_with("area:")
}

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let c = manager.get_connection();
        c.execute_unprepared(UP).await?;
        let now = docket_core::clock::now();
        for p in c.query_all_raw(statement(PROJECTS, vec![])).await? {
            let mut project = ProjectDump {
                slug: p.try_get_by_index(0)?,
                keys: p.try_get_by_index(1)?,
                themes: p.try_get_by_index(2)?,
                skills: p.try_get_by_index(3)?,
                ..ProjectDump::default()
            };
            let (items, events, rids) = project_rows(c, &mut project).await?;
            let slug = project.slug.clone();
            let rows = Rows {
                project: &project,
                items: items.iter().collect(),
                events: events.iter().collect(),
            };
            let changes = plan(&rows, Rules::default());
            let mut ids: BTreeMap<String, i64> = BTreeMap::new();
            for (name, about) in &changes.labels {
                if is_area_theme(name) {
                    continue;
                }
                let id: i64 = c
                    .query_one_raw(statement(
                        "INSERT INTO labels (project, name, description) VALUES (?, ?, ?) \
                         ON CONFLICT (project, lower(name)) DO UPDATE SET name=labels.name \
                         RETURNING id",
                        vec![
                            slug.clone().into(),
                            name.clone().into(),
                            Some(about.clone()).filter(|a| !a.is_empty()).into(),
                        ],
                    ))
                    .await?
                    .ok_or(DbErr::RecordNotInserted)?
                    .try_get_by_index(0)?;
                ids.insert(name.clone(), id);
            }
            for change in &changes.changes {
                match change {
                    Change::Label { id, label } => {
                        let (Some(rid), Some(label_id)) = (rids.get(id), ids.get(label)) else {
                            continue;
                        };
                        let set = c
                            .execute_raw(statement(
                                "INSERT INTO item_labels (rid, label_id) VALUES (?, ?) \
                                 ON CONFLICT DO NOTHING",
                                vec![(*rid).into(), (*label_id).into()],
                            ))
                            .await?
                            .rows_affected();
                        if set > 0 {
                            pending(c, &slug, *rid).await?;
                        }
                    }
                    Change::BecomesLabel { id, label } => {
                        if let Some(rid) = rids.get(id) {
                            drop_concept(c, &slug, *rid, "label", label, &now).await?;
                            pending(c, &slug, *rid).await?;
                        }
                    }
                    _ => {}
                }
            }
        }
        Ok(())
    }

    /// The drops stay: the tables go and the tags and groups they came from are still on the items.
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(DOWN).await?;
        Ok(())
    }
}
