//! Areas as rows: a name, a description, a position and a priority, and each item's area as a key to
//! one. The key stays empty until a later step gives every item its area.

use sea_orm_migration::prelude::*;

const UP: &str = r#"
CREATE TABLE areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  name TEXT COLLATE "C" NOT NULL CHECK (btrim(name) <> ''),
  description TEXT COLLATE "C",
  position BIGINT NOT NULL,
  priority TEXT COLLATE "C" CHECK (priority IN ('critical', 'high', 'normal', 'low')),
  UNIQUE (project, position) DEFERRABLE INITIALLY IMMEDIATE
);
CREATE UNIQUE INDEX areas_name ON areas(project, lower(name));

ALTER TABLE items ADD COLUMN area_id BIGINT REFERENCES areas(id);
CREATE INDEX items_area ON items(area_id);
"#;

const DOWN: &str = "ALTER TABLE items DROP COLUMN IF EXISTS area_id; DROP TABLE IF EXISTS areas;";

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UP).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(DOWN).await?;
        Ok(())
    }
}
