//! Publications as rows: each commit a squash wrote to a project's published ref, the work snapshot
//! whose tree it carries, and the plans it covers. A published sha is recorded once per project, and
//! the newest row is where the next squash starts.

use sea_orm_migration::prelude::*;

const UP: &str = r#"
CREATE TABLE publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  published_sha TEXT COLLATE "C" NOT NULL CHECK (published_sha ~ '^[0-9a-f]{40}([0-9a-f]{24})?$'),
  work_sha TEXT COLLATE "C" NOT NULL CHECK (work_sha ~ '^[0-9a-f]{40}([0-9a-f]{24})?$'),
  created_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (project, published_sha)
);
CREATE INDEX publications_newest ON publications(project, created_at DESC, id DESC);

CREATE TABLE publication_plans (
  publication BIGINT NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  rid BIGINT NOT NULL REFERENCES items(rid),
  PRIMARY KEY (publication, rid)
);
CREATE INDEX publication_plans_rid ON publication_plans(rid);
"#;

const DOWN: &str = "DROP TABLE IF EXISTS publication_plans; DROP TABLE IF EXISTS publications;";

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(UP).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(DOWN).await?;
        Ok(())
    }
}
