//! Releases as rows: a name, a position, a target date and a shipped time, and each item's release
//! as a key to one. The planner places them: the releases fact in order, then each theme named as a
//! version; an item with no theme is in the current release, and one whose theme is no release takes
//! its plan's release, else the backlog, and keeps the theme. The releases fact is removed.

use std::collections::BTreeMap;

use sea_orm::ConnectionTrait;
use sea_orm_migration::prelude::*;

use docket_core::migrate::{Change, OldItem, OldProject, Rows, Rules, Themes, plan};

use crate::statement;

const UP: &str = r#"
CREATE TABLE releases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  name TEXT COLLATE "C" NOT NULL CHECK (name <> '' AND name !~ '\s'),
  position BIGINT NOT NULL,
  target_date TEXT COLLATE "C",
  shipped_at TEXT COLLATE "C",
  note TEXT COLLATE "C",
  UNIQUE (project, name),
  UNIQUE (project, position) DEFERRABLE INITIALLY IMMEDIATE
);

ALTER TABLE items ADD COLUMN release_id BIGINT REFERENCES releases(id);
CREATE INDEX items_release ON items(release_id);
"#;

const DOWN: &str =
    "ALTER TABLE items DROP COLUMN IF EXISTS release_id; DROP TABLE IF EXISTS releases;";

/// The rules the placement turns on, as decided: a plan's later children come back into its
/// release, and an item whose theme is no release takes its plan's release, else the backlog.
const RULES: Rules = Rules {
    themes: Themes::Plan,
};

const PROJECTS: &str = "SELECT slug, keys, themes, skills FROM projects ORDER BY slug";

/// Each item of a project with what the planner reads: the items that opened it and those related.
const ITEMS: &str = "SELECT i.id, i.title, i.state, i.theme, i.group_name, i.tags, \
    COALESCE((SELECT array_agg(o.id ORDER BY o.id) FROM links l JOIN items o ON o.rid=l.to_rid \
      WHERE l.rid=i.rid AND l.kind='opened'), '{}'), \
    COALESCE((SELECT array_agg(o.id ORDER BY o.id) FROM links l JOIN items o ON o.rid=l.to_rid \
      WHERE l.rid=i.rid AND l.kind='related'), '{}'), \
    i.opened_at, i.updated_at \
    FROM items i WHERE i.project=? ORDER BY i.key, i.num";

async fn project_rows<C: ConnectionTrait>(c: &C) -> Result<Vec<(OldProject, Vec<OldItem>)>, DbErr> {
    let mut out = Vec::new();
    for p in c.query_all_raw(statement(PROJECTS, vec![])).await? {
        let project = OldProject {
            slug: p.try_get_by_index(0)?,
            keys: p.try_get_by_index(1)?,
            themes: p.try_get_by_index(2)?,
            skills: p.try_get_by_index(3)?,
            ..OldProject::default()
        };
        let mut items = Vec::new();
        for r in c
            .query_all_raw(statement(ITEMS, vec![project.slug.clone().into()]))
            .await?
        {
            let tags: serde_json::Value = r.try_get_by_index(5)?;
            items.push(OldItem {
                project: project.slug.clone(),
                id: r.try_get_by_index(0)?,
                title: r.try_get_by_index(1)?,
                state: r.try_get_by_index(2)?,
                theme: r.try_get_by_index(3)?,
                group: r.try_get_by_index(4)?,
                tags: serde_json::from_value(tags).unwrap_or_default(),
                opened: r.try_get_by_index(6)?,
                related: r.try_get_by_index(7)?,
                opened_at: r.try_get_by_index(8)?,
                updated_at: r.try_get_by_index(9)?,
                ..OldItem::default()
            });
        }
        out.push((project, items));
    }
    Ok(out)
}

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let c = manager.get_connection();
        c.execute_unprepared(UP).await?;
        for (project, items) in project_rows(c).await? {
            let rows = Rows {
                project: &project,
                items: items.iter().collect(),
                events: Vec::new(),
            };
            let changes = plan(&rows, RULES);
            let mut ids: BTreeMap<String, i64> = BTreeMap::new();
            for r in &changes.releases {
                let id: i64 = c
                    .query_one_raw(statement(
                        "INSERT INTO releases (project, name, position) VALUES (?, ?, ?) RETURNING id",
                        vec![
                            project.slug.clone().into(),
                            r.name.clone().into(),
                            <i64 as TryFrom<usize>>::try_from(r.position)
                                .unwrap_or(i64::MAX)
                                .into(),
                        ],
                    ))
                    .await?
                    .ok_or(DbErr::RecordNotInserted)?
                    .try_get_by_index(0)?;
                ids.insert(r.name.clone(), id);
            }
            for change in &changes.changes {
                let Change::InRelease {
                    id,
                    release: Some(name),
                } = change
                else {
                    continue;
                };
                c.execute_raw(statement(
                    "UPDATE items SET release_id=? WHERE project=? AND id=?",
                    vec![
                        ids.get(name).copied().into(),
                        project.slug.clone().into(),
                        id.clone().into(),
                    ],
                ))
                .await?;
            }
        }
        c.execute_unprepared("UPDATE projects SET skills = skills - 'releases'")
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(DOWN).await?;
        Ok(())
    }
}
