//! One row per attempt at an item, rebuilt for the items already held from their events.

use sea_orm_migration::prelude::*;

const UP: &str = r#"
CREATE TABLE assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rid BIGINT NOT NULL REFERENCES items(rid) ON DELETE CASCADE,
  assignee TEXT COLLATE "C" NOT NULL,        -- agent | owner
  kind TEXT COLLATE "C" NOT NULL CHECK (kind IN ('claim', 'ask')),
  started_at TEXT COLLATE "C" NOT NULL,
  ended_at TEXT COLLATE "C",                 -- NULL: under way now
  outcome TEXT COLLATE "C" CHECK (outcome IN ('landed', 'conflict', 'gate', 'blocked', 'failed')),
  note TEXT COLLATE "C",
  actor TEXT COLLATE "C",                    -- owner | agent, the key that last moved it; NULL when rebuilt
  branch TEXT COLLATE "C",
  host TEXT COLLATE "C" NOT NULL,            -- the host whose key wrote the claim
  machine TEXT COLLATE "C",                  -- the host a job runs on
  runner TEXT COLLATE "C",
  model TEXT COLLATE "C",
  effort TEXT COLLATE "C",
  role TEXT COLLATE "C",
  job TEXT COLLATE "C",
  tokens_in BIGINT,
  tokens_out BIGINT,
  cost_reported DOUBLE PRECISION,
  CHECK (outcome IS NULL OR (ended_at IS NOT NULL AND kind = 'claim'))
);
CREATE UNIQUE INDEX assignments_open ON assignments(rid) WHERE ended_at IS NULL;
CREATE INDEX assignments_item ON assignments(rid, id);
"#;

const DOWN: &str = "DROP TABLE IF EXISTS assignments;";

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let c = manager.get_connection();
        c.execute_unprepared(UP).await?;
        crate::assignments::rebuild_all(c).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager.get_connection().execute_unprepared(DOWN).await?;
        Ok(())
    }
}
