-- docket: one database for every project. Every count is a query, never a column.
-- Text compares bytewise (COLLATE "C"), whatever the database's locale, so every order is the same
-- on every host.

CREATE TABLE projects (
  slug TEXT COLLATE "C" PRIMARY KEY,
  keys JSONB NOT NULL DEFAULT '[]',          -- [{key, kind, meaning, turn}]
  remotes JSONB NOT NULL DEFAULT '[]',       -- [origin url]
  themes JSONB NOT NULL DEFAULT '[]',        -- [{name, note}]
  cite_roots JSONB NOT NULL DEFAULT '[]',    -- [path], relative to a root binding
  repos JSONB NOT NULL DEFAULT '[]',         -- [path], where a sha may resolve
  fleet_repo TEXT COLLATE "C",
  integration_ref TEXT COLLATE "C",
  worktree_hint TEXT COLLATE "C",
  test_hint TEXT COLLATE "C",
  skills JSONB NOT NULL DEFAULT '{}',        -- {fact: text}, the per-project facts the skills render
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL
);

-- Never dumped: where a project sits on a host.
CREATE TABLE roots (
  host TEXT COLLATE "C" NOT NULL,
  path TEXT COLLATE "C" NOT NULL,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  bound_at TEXT COLLATE "C" NOT NULL,
  how TEXT COLLATE "C" NOT NULL,             -- auto | bind | import
  PRIMARY KEY (host, path)
);

CREATE TABLE items (
  rid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  key TEXT COLLATE "C" NOT NULL,
  num BIGINT NOT NULL CHECK (num > 0),
  id TEXT COLLATE "C" GENERATED ALWAYS AS (key || num::text) STORED,
  title TEXT COLLATE "C" NOT NULL CHECK (title <> ''),
  state TEXT COLLATE "C" NOT NULL CHECK (state IN ('open', 'done', 'dropped')),
  turn TEXT COLLATE "C" CHECK (turn IN ('agent', 'user')),
  turn_note TEXT COLLATE "C",
  asked_at TEXT COLLATE "C",
  claim_branch TEXT COLLATE "C",
  claim_host TEXT COLLATE "C",
  claim_since TEXT COLLATE "C",
  claim_runner TEXT COLLATE "C",             -- codex | claude | remote, when a fleet job holds the claim
  claim_job TEXT COLLATE "C",                -- that job's name in its runner
  claim_on TEXT COLLATE "C",                 -- the host the job runs on, when it is not claim_host
  wait_on TEXT COLLATE "C" CHECK (wait_on IN ('item', 'condition')),
  wait_item BIGINT REFERENCES items(rid) DEFERRABLE,  -- deferred by a copy, which writes in rid order
  wait_ref TEXT COLLATE "C",
  wait_since TEXT COLLATE "C",
  decision TEXT COLLATE "C",
  decided_at TEXT COLLATE "C",
  resolution TEXT COLLATE "C",
  superseded_by BIGINT REFERENCES items(rid) DEFERRABLE,
  scope TEXT COLLATE "C" CHECK (scope IN ('inbox', 'later')),  -- NULL: in the release
  complexity TEXT COLLATE "C" CHECK (complexity IN ('high', 'medium', 'low')),
  group_name TEXT COLLATE "C",
  theme TEXT COLLATE "C",
  rank BIGINT,
  tags JSONB NOT NULL DEFAULT '[]',
  body TEXT COLLATE "C" NOT NULL DEFAULT '',
  conflict BIGINT NOT NULL DEFAULT 0,
  opened_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (project, key, num),
  CHECK ((state = 'open') = (turn IS NOT NULL)),
  CHECK ((claim_branch IS NULL) = (claim_host IS NULL) AND (claim_branch IS NULL) = (claim_since IS NULL)),
  CHECK (claim_branch IS NULL OR (state = 'open' AND turn = 'agent')),
  CHECK ((wait_on IS NULL) = (wait_since IS NULL)),
  CHECK (wait_on IS NULL OR state = 'open'),
  CHECK (wait_on IS DISTINCT FROM 'item' OR wait_item IS NOT NULL),
  CHECK (wait_on IS DISTINCT FROM 'condition' OR wait_ref IS NOT NULL),
  CHECK (wait_on IS NOT NULL OR (wait_item IS NULL AND wait_ref IS NULL)),
  CHECK (wait_item IS NULL OR wait_item <> rid),
  CHECK (state = 'open' OR resolution IS NOT NULL),
  CHECK (superseded_by IS NULL OR state = 'dropped'),
  CHECK ((decision IS NULL) = (decided_at IS NULL))
);

CREATE INDEX items_project_state ON items(project, state);
CREATE INDEX items_wait ON items(wait_item);

CREATE TABLE events (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT COLLATE "C" NOT NULL UNIQUE,
  project TEXT COLLATE "C" NOT NULL REFERENCES projects(slug),
  rid BIGINT REFERENCES items(rid),
  at TEXT COLLATE "C" NOT NULL,
  host TEXT COLLATE "C" NOT NULL,
  branch TEXT COLLATE "C",
  kind TEXT COLLATE "C" NOT NULL CHECK (kind IN ('opened', 'claimed', 'released', 'waited', 'resumed',
    'asked', 'replied', 'decided', 'closed', 'dropped', 'reopened', 'edited', 'renumbered',
    'claim_lost', 'queue', 'legacy', 'audited')),
  note TEXT COLLATE "C",
  data JSONB                                 -- {field: value}: a landing, a gates result, an audit
);

CREATE INDEX events_item ON events(rid, at);
CREATE INDEX events_project_at ON events(project, at);

CREATE TABLE links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rid BIGINT NOT NULL REFERENCES items(rid) ON DELETE CASCADE,
  kind TEXT COLLATE "C" NOT NULL CHECK (kind IN ('related', 'opened', 'cites_file', 'cites_test')),
  to_rid BIGINT REFERENCES items(rid) ON DELETE CASCADE,
  to_path TEXT COLLATE "C",
  to_line BIGINT,
  CHECK ((to_rid IS NOT NULL) <> (to_path IS NOT NULL)),
  UNIQUE (rid, kind, to_rid, to_path, to_line)
);

CREATE INDEX links_to ON links(to_rid);
CREATE INDEX links_path ON links(to_path);

-- What full-text search reads: each item's id, title, body and cited paths, weighted title, id, files,
-- then body. The characters the text parser would join into a path, address, URL or markup tag are
-- read as spaces, so each part of `src/a.rs:4` is found on its own.
CREATE TABLE search (
  rid BIGINT PRIMARY KEY REFERENCES items(rid) ON DELETE CASCADE,
  id TEXT COLLATE "C" NOT NULL,
  title TEXT COLLATE "C" NOT NULL,
  body TEXT COLLATE "C" NOT NULL,
  files TEXT COLLATE "C" NOT NULL DEFAULT '',
  doc TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', translate(title, '/:<>@?=&#%~+', '            ')), 'A') ||
    setweight(to_tsvector('simple', id), 'B') ||
    setweight(to_tsvector('simple', translate(files, '/:<>@?=&#%~+', '            ')), 'C') ||
    setweight(to_tsvector('simple', translate(body, '/:<>@?=&#%~+', '            ')), 'D')
  ) STORED
);

CREATE INDEX search_doc ON search USING GIN (doc);

-- Rows changed by a committed transaction whose dump has not reached the git repo yet.
CREATE TABLE pending_dump (
  rid BIGINT PRIMARY KEY,
  project TEXT COLLATE "C" NOT NULL
);

-- Never dumped: each chore's last run on a host, kept so a failure is seen.
CREATE TABLE chores (
  name TEXT COLLATE "C" NOT NULL,
  project TEXT COLLATE "C" NOT NULL DEFAULT '',
  at DOUBLE PRECISION,
  seconds DOUBLE PRECISION,
  result TEXT COLLATE "C",
  failures BIGINT NOT NULL DEFAULT 0,
  ok BIGINT,
  PRIMARY KEY (name, project)
);

CREATE TABLE meta (
  k TEXT COLLATE "C" PRIMARY KEY,
  v TEXT COLLATE "C" NOT NULL
);
